In [2]:

import numpy as np

# 1. convert a list of numeric value into a one-dimensional NumPy array

original_list=[12.23, 13.32, 100, 36.32]
print(f"Original List: {original_list}")
arr=np.array(original_list)
print(f"One dimensional numpy array:{arr}")

Original List: [12.23, 13.32, 100, 36.32]
One dimensional numpy array:[ 12.23  13.32 100.    36.32]


In [ ]:
# 2 3x3 matrix with values ranging from 2 to 10.

arr=np.arange(2,11).reshape(3,3)
print(arr)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [ ]:
# 3.create a null vector of size 10 and update sixth value to 11

arr=np.zeros(10)
print(arr)
arr[6]=11
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


In [ ]:
# 4.reverse an array 

original_array=np.array([12 ,13 ,14 ,15 ,16 ,17 ,18 ,19 ,20 ,21 ,22 ,23 ,24 ,25 ,26 ,27 ,28 ,29 ,30 ,31 ,32 ,33 ,34 ,35 ,36 ,37])
print("Original Array")
print(original_array)
reverserd_array=original_array[::-1]
print("Reverserd Arrray")
print(reverserd_array)

Original Array
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
Reverserd Arrray
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


In [ ]:
# 5. 2d array with 1 on the border and 0
                 
array=np.ones((5,5))

print("Original Array")
print(array)

array[1:-1,1:-1]=0
print("Modified Array")
print(array)

Original Array
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Modified Array
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [53]:
# 6 add a border (filled with 0's) around an existing array

array=np.ones((3,3))
print("Original Array")
print(array)
border=np.zeros((5,5))
border[1:-1,1:-1]=array
print("0 on the border and 1 inside in the array")
print(border)

Original Array
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
0 on the border and 1 inside in the array
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
# 7.Create a 8x8 matrix and fill it with a checkerboard pattern

arr=np.ones((8,8),dtype='i')
print(arr)
print()
arr[0::2,0::2]=0
arr[1::2,1::2]=0
print(arr)

[[1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]]

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
# 8.convert a list and tuple into arrays.

list1=[1,2,3,4,5,6,7,8]
tuple1=(8,4,6,1,2,3)

print("List to array :")
arr1=np.array(list1)
print(arr1)

print("Tuple to array :")
arr2=np.array(tuple1).reshape(2,3)

print(arr2)

List to array :
[1 2 3 4 5 6 7 8]
Tuple to array :
[[8 4 6]
 [1 2 3]]


In [ ]:
#9.append values to the end of an array


arr=np.array([10, 20, 30])

arr=np.append(arr,[40,50,60,70,80,90])
print(arr)

[10 20 30 40 50 60 70 80 90]


In [ ]:
# 10.find the real and imaginary parts of an array of complex numbers


arr=np.array( [ 1.00000000+0.j, 0.70710678+0.70710678j])
print(f"Original Array:{arr}")
real=arr.real
imaginary=arr.imag
print("Real part of the array :")
print(real)
print("Imaginary part of the array :")
print(imaginary)

Original Array:[1.        +0.j         0.70710678+0.70710678j]
Real part of the array :
[1.         0.70710678]
Imaginary part of the array :
[0.         0.70710678]


In [ ]:
# 11 number of elements of an array, length of one array element in bytes and total bytes consumed by the elements

arr=np.array([1,2,3])
print(f"Size of the array :{arr.size}")
print(f"Length of one array element in bytes: {arr.itemsize}")
print(f"Total bytes consumed by the elements of the array: {arr.size * arr.itemsize}")

Size of the array :3
Length of one array element in bytes: 8
Total bytes consumed by the elements of the array: 24


In [ ]:
# 12 common values between two arrays

arr1=np.array([ 0,10,20,40,60])
arr2=np.array([10, 30, 40])

print(f"Array1: {arr1}")
print(f"Array2: {arr2}")
print(f"Common values between two arrays:\n{np.intersect1d(arr1,arr2)}")

Array1: [ 0 10 20 40 60]
Array2: [10 30 40]
Common values between two arrays:
[10 40]


In [ ]:
# 13 the set difference of two arrays.

arr1=np.array( [ 0 ,10 ,20 ,40 ,60 ,80])
arr2=np.array([10, 30, 40, 50, 70, 90])

print(f"Array1: {arr1}")
print(f"Array2: {arr2}")
print(f"Set difference between two arrays:\n {np.setdiff1d(arr1,arr2)}")

Array1: [ 0 10 20 40 60 80]
Array2: [10 30 40 50 70 90]
Set difference between two arrays:
 [ 0 20 60 80]


In [ ]:
# 14 the set exclusive-or of two arrays.

arr1=np.array([ 0 ,10 ,20 ,40 ,60 ,80])
arr2=np.array([10, 30, 40, 50, 70])

print(f"Array1: {arr1}")
print(f"Array2: {arr2}")
print(f"Unique values that are in only one (not both) of the input arrays: \n{np.setxor1d(arr1,arr2)}")

Array1: [ 0 10 20 40 60 80]
Array2: [10 30 40 50 70]
Unique values that are in only one (not both) of the input arrays: 
[ 0 20 30 50 60 70 80]


In [ ]:
#15 compare two arrays using numpy.

a=np.array([1,2])
b=np.array([4,5])

print(a>b)
print(a>=b)
print(a<b)
print(a<=b)

[False False]
[False False]
[ True  True]
[ True  True]


In [ ]:
#15  to save a NumPy array to a text file

a=np.ones((5,5))
np.savetxt("array.txt",a)

In [72]:
# 16 create a contiguous flattened array.

a=np.array([[10,20,30],
            [20,40,50]])

print("Original array:")
print(a)
print("New Flattened Array: ")
print(a.flatten())

Original array:
[[10 20 30]
 [20 40 50]]
New Flattened Array: 
[10 20 30 20 40 50]


In [59]:
# 17 to change the data type of an array.

a=np.array([[ 2 ,4 ,6],
           [ 6 ,8 ,10]],dtype='int32')
print(a)
print(f"Data type of the array x is: {a.dtype}")
a=a.astype(np.float64)
print(f"New Type: {a.dtype}")
print(a)

[[ 2  4  6]
 [ 6  8 10]]
Data type of the array x is: int32
New Type: float64
[[ 2.  4.  6.]
 [ 6.  8. 10.]]


In [67]:
# 18 3-D array with ones on a diagonal and zeros elsewhere.

arr=np.zeros((3,3))
np.fill_diagonal(arr,1)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [73]:
# 19. Write a Python program to create an array which looks like below array.

arr = np.tril(np.ones((4, 3)))
print(arr)



[[1. 0. 0.]
 [1. 1. 0.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [83]:
# 20  to concatenate two 2-dimensional arrays

arr1=np.array([[0, 1, 3], [5, 7, 9]])
arr2=np.array([[0, 2, 4], [6, 8, 10]])

arr3=np.concatenate((arr1,arr2),axis=1)
print(arr3)

[[ 0  1  3  0  2  4]
 [ 5  7  9  6  8 10]]


In [4]:
# 21 to make an array immutable (read-only)

arr1=np.array([0, 1, 3, 5, 7, 9])
print("Test the array is read-only or not:")
arr1.setflags(write=False)
print("Try to change the value of the first element:")
arr1[0]=5


Test the array is read-only or not:
Try to change the value of the first element:


ValueError: assignment destination is read-only

In [4]:
# 22 to create an array of (3, 4) shape, multiply every element value by 3 and display the new array.

arr=np.arange(0,12).reshape(3,4)
print("Original array elements :")
print(arr)

print("New array elements:")
print(arr*3)

Original array elements :
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
New array elements:
[[ 0  3  6  9]
 [12 15 18 21]
 [24 27 30 33]]


In [9]:
#23 to convert a NumPy array into Python list structure.

arr=np.array([[0,1],[2,3],[4,5]])
print(f"Original Array Elements:\n {arr}")

print("Array to list:")
print(arr.tolist())

Original Array Elements:
 [[0 1]
 [2 3]
 [4 5]]
Array to list:
[[0, 1], [2, 3], [4, 5]]


In [10]:
#24  NumPy array into Python list structure.
arr=np.array([ 0.26153123,0.52760141,0.5718299,0.5927067,0.7831874,0.69746349,
0.35399976, 0.99469633, 0.0694458, 0.54711478])
print(f"Original array elements: {arr}")
arr=np.round(arr,decimals= 3)
print("Print array values with precision 3:")
print(arr.tolist())


Original array elements: [0.26153123 0.52760141 0.5718299  0.5927067  0.7831874  0.69746349
 0.35399976 0.99469633 0.0694458  0.54711478]
Print array values with precision 3:
[0.262, 0.528, 0.572, 0.593, 0.783, 0.697, 0.354, 0.995, 0.069, 0.547]


In [9]:
#25 suppresses the use of scientific notation for small numbers in numpy array.

arr=np.array([ 1.60000000e-10 ,1.60000000e+00 ,1.20000000e+03 ,2.35000000e-01])
print("Print array values with precision 3")
np.set_printoptions(precision=3,suppress=True)
print(arr)

Print array values with precision 3
[   0.       1.6   1200.       0.235]


In [27]:
# 26 Write a Python program to how to add an extra column to an numpy array.

arr=np.array([[ 10,20,30],[40, 50,60]])
arr2=np.array([[100],[200]])

arr=np.hstack((arr,arr2))
print(arr)

[[ 10  20  30 100]
 [ 40  50  60 200]]


In [28]:
# 27  to remove specific elements in a numpy array.

arr=np.array([ 10 ,20 ,30 ,40 ,50 ,60 ,70,80 ,90 ,100])
np.delete(arr,[0,3,4])

array([ 20,  30,  60,  70,  80,  90, 100])